global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "fastapi-app"
    static_configs:
      - targets: ["app:80"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

