global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'your_app'
    static_configs:
      - targets: ['your_app:8000']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']